### PR TITLE
Script to fetch pinyin based on raw txt file

### PR DESCRIPTION
**Pull request by suokunlong**
Python3 script to fetch pinyin based on raw txt file. Results will be saved in the same dir with same filename with suffix "dict_".

format of the txt file should be 
"词语 freq # comments"
"词语 freq" or 
"词语"

However only only the fist two parts (i.e.m 词语 and freq) will be retained in the result.
The generated result file can be imported to ibus-libpinyin as user dicts directly.

Author: Kevin Suo <suokunlong@126.com>
This script is written specially for libpinyin, but may be used for any other suitable purposes.

Licensed under GNU Public License v3 or above.

### CODE REVIEW

**Comment by epico** [comment]
Here are some comments about the script:

1. Please try to figure out the pinyin by using data only from libpinyin
   - The content from web site may cause copyright issue
   - Sometimes we can guess all the possible pinyin for the phrase
2. As this tool will be used with ibus-libpinyin, please create the pull request for ibus-libpinyin instead
   - The scripts2 in libpinyin is used for code generation
3. Please update the GPLv3+ header as specified in https://www.gnu.org/licenses/gpl.html

Feel free to contact me, if you have any questions about the script.

**Comment by suokunlong** [comment]
> Please try to figure out the pinyin by using data only from libpinyin

How can I do that? Is there any code examples? If not, concerning the license issue I plan to use "pypinyin" instead.

The reason why I wrote this script is that, I plan to build a user-contributed 词语 list (with or without freqs), so that libpinyin can include more 词语 which may certainly speed up the input speed. 
The procedure is that: 1. Prepare user-contributed or self-prepared 词语 list in txt format; 2. use this script to quickly generate pinyin for the 词语 list, which can then be used to be imported to ibus-libpinyin.

Actually I have already prepared some lists of words, including the 现代汉语常用词 list with freqs. I have tested it and it dramatically speeds up my type in experience.

**Comment by suokunlong** [comment]
I think you guys are too cautious about the license/copyright issue.

I have added the script (as well as some word list) to my own repo:
https://github.com/suokunlong/libpinyin-dict

If you feel OK that some dicts can be merged, please do so.

**Comment by epico** [comment]
Thanks for your work!

I have added your git repo URL to libpinyin wiki.
URL: https://github.com/libpinyin/libpinyin/wiki

**Pull request closed without merging**
