### PR TITLE
include libzhuyin opengram model data

### PR DESCRIPTION
**Pull request by Brli**
I change the directory name to be a bit ugly

maybe consider merge the two `Makefile.am` into one?

### CODE REVIEW

**Comment by epico** [comment]
Sorry, I think separate package is easier to maintain and smaller for downloads.

**Comment by Brli** [comment]
Yeah, am just saying the lack of taste of naming, however, is there COC for
dir/file naming in this project?

BTW, I cannot test the patch myself (I mean, does it really works? Or it
just generate files as if it does.)

I've patched fcitx-libzhuyin also, but it crashes unconditionally, and ibus
varient seems to bundle its own lib instead of using this as shared AFAIK

Peng Wu <notifications@github.com> 於 2020年9月4日 週五 下午1:34 寫道：

**Comment by epico** [comment]
Why do you want to include ibus-libzhuyin data into libpinyin repo?

I think you could try to bundle the data like fcitx-zhuyin or ibus-libpinyin.

BTW, I am not familiar with fcitx code...

**Comment by Brli** [comment]
well, because it is the library? I mean, you don't then need to have two or more same set of data in system if you have more than one IME framework installed.

**Comment by epico** [comment]
fcitx-zhuyin has its own data in the tar ball, and is different from ibus-libzhuyin data.

**Comment by Brli** [comment]
Afaik, that is just a matter of version differences, or are there also
format difference?

**Comment by epico** [comment]
The zhuyin data is different.

**Pull request closed without merging**
