### PR TITLE
Replace --version-script with -exported_symbols_list for LLVM ld

### PR DESCRIPTION
**Pull request by Inokinoki**
Currently, use `AC_CANONICAL_HOST` to detect OS.
Remove --version-script option from `LD_FLAG` when on macOS.

### CODE REVIEW

**Comment by Inokinoki** [comment]
According to the discussion, detecting compiler set may be a better choice ?

**Comment by Inokinoki** [comment]
Will try updating CMakeLists.txt files soon

**Comment by epico** [comment]
Right, detect the compiler is a better option.

**Comment by epico** [comment]
Could you try to use -exported_symbols_list with clang?

The libpinyin.ver is used to only export C ABI from libpinyin.

**Comment by epico** [comment]
URL: https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryDesignGuidelines.html

**Comment by epico** [comment]
Thanks for the patch!

**Comment by Arfrever** [comment]
Compiler and linker are independent.
It is possible to use many combinations of compiler and linker.
Both GCC and Clang support `-fuse-ld=...` option to specify linker.
(E.g. `-fuse-ld=bfd`, `-fuse-ld=gold`, `-fuse-ld=lld`)

This commit (ccf9c76a38c8a784535499d806843445e1ad385e) has broken hiding of symbols intended to be private when using Clang compiler on Linux systems. I.e. there is no build failure, but all symbols are exported.

In libpinyin, generated Makefiles actually do not specify calling compiler directly, but `libtool`:
```
/bin/sh ../libtool  --tag=CXX   --mode=link clang++ ... -Wl -exported_symbols_list ./libpinyin.exp -version-info 13:0 ...
```
This `libtool` apparently does not pass `-exported_symbols_list` to compiler when it calls compiler.

The proper way to pass arguments from compiler to linker is `-Wl,${argument_for_linker}` without any whitespace after `-Wl`, e.g. `-Wl,-exported_symbols_list`.
Multiple arguments can be separated by `,` characters, e.g. `-Wl,A,B,C` results in passing `A B C` to linker.

As solution:
1. Compiler (Clang versus non-Clang) should not be checked at all.
2. I suggest to check if `-Wl,--version-script` is supported and use `-Wl,-exported_symbols_list` otherwise.
Both GNU linkers (BFD and GOLD) and LLD linker support `--version-script` option, but they also support `--entry` option with short alias `-e`. BFD linker called with `-exported_symbols_list` prints:
```
ld: warning: cannot find entry symbol xported_symbols_list; defaulting to ...
```

**Comment by Inokinoki** [comment]
> Compiler and linker are independent.
> It is possible to use many combinations of compiler and linker.
> Both GCC and Clang support `-fuse-ld=...` option to specify linker.
> (E.g. `-fuse-ld=bfd`, `-fuse-ld=gold`, `-fuse-ld=lld`)
> 
> This commit ([ccf9c76](https://github.com/libpinyin/libpinyin/commit/ccf9c76a38c8a784535499d806843445e1ad385e)) has broken hiding of symbols intended to be private when using Clang compiler on Linux systems. I.e. there is no build failure, but all symbols are exported.
> 
> In libpinyin, generated Makefiles actually do not specify calling compiler directly, but `libtool`:
> 
> ```
> /bin/sh ../libtool  --tag=CXX   --mode=link clang++ ... -Wl -exported_symbols_list ./libpinyin.exp -version-info 13:0 ...
> ```
> 
> This `libtool` apparently does not pass `-exported_symbols_list` to compiler when it calls compiler.
> 
> The proper way to pass arguments from compiler to linker is `-Wl,${argument_for_linker}` without any whitespace after `-Wl`, e.g. `-Wl,-exported_symbols_list`.
> Multiple arguments can be separated by `,` characters, e.g. `-Wl,A,B,C` results in passing `A B C` to linker.
> 
> As solution:
> 
> 1. Compiler (Clang versus non-Clang) should not be checked at all.
> 2. I suggest to check if `-Wl,--version-script` is supported and use `-Wl,-exported_symbols_list` otherwise.
>    Both GNU linkers (BFD and GOLD) and LLD linker support `--version-script` option, but they also support `--entry` option with short alias `-e`. BFD linker called with `-exported_symbols_list` prints:
> 
> ```
> ld: warning: cannot find entry symbol xported_symbols_list; defaulting to ...
> ```

Thanks very much for the detailed explanations!

I wonder if https://github.com/libpinyin/libpinyin/pull/142 can help with the broken exported symbols.
I did not know how to check the linker option support through autotools.
So, in that PR, the LLD linker is checked to determine which LDFLAGS to use.

In my environment, the `--version-script` does not seem to be supported:

```
> ld --version-script=test
ld: unknown option: --version-script=test
```

I did see the option is supported in the [ldd man page hosted by Ubuntu](https://manpages.ubuntu.com/manpages/disco/man1/ld.lld.1.html).

So, I guess it might be differences between different versions of `lld`. Here is the version info of the mine:

```
@(#)PROGRAM:ld  PROJECT:ld64-530
BUILD 18:57:17 Dec 13 2019
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 11.0.0, (clang-1100.0.33.17) (static support for 23, runtime is 23)
TAPI support using: Apple TAPI version 11.0.0 (tapi-1100.0.11)
```

**Comment by Arfrever** [comment]
So LLD is actually group of several linkers, as seen in:
https://github.com/llvm/llvm-project/blob/f2710d4b576053d405af7a0e2a62ea06d5a978e3/lld/tools/lld/lld.cpp#L13-L24
https://github.com/llvm/llvm-project/blob/f2710d4b576053d405af7a0e2a62ea06d5a978e3/lld/tools/lld/lld.cpp#L54-L61
https://github.com/llvm/llvm-project/blob/f2710d4b576053d405af7a0e2a62ea06d5a978e3/lld/tools/lld/lld.cpp#L68-L76

GNU flavor (`ld.lld` or `lld -flavor gnu`) supports `--version-script` option. Other flavors do not.
```
$ echo '{global: *;};' > test
$ ld.lld --version-script=test
ld.lld: error: no input files
$ lld -flavor gnu --version-script=test
lld: error: no input files
$ ld64.lld --version-script=test
ld64.lld: warning: ignoring unknown argument: --version-script=test
ld64.lld: error: -arch not specified and could not be inferred
$ lld -flavor darwin --version-script=test
lld: warning: ignoring unknown argument: --version-script=test
lld: error: -arch not specified and could not be inferred
$ lld-link --version-script=test
lld-link: warning: ignoring unknown argument '--version-script=test'
lld-link: error: no input files
$ lld -flavor link --version-script=test
lld: warning: ignoring unknown argument '--version-script=test'
lld: error: no input files
$ wasm-ld --version-script=test
wasm-ld: error: unknown argument: --version-script=test
wasm-ld: error: no output file specified
wasm-ld: error: no input files
$ lld -flavor wasm --version-script=test
lld: error: unknown argument: --version-script=test
lld: error: no output file specified
lld: error: no input files
```

`ld.lld`, `ld64.lld`, `ld64.lld.darwinnew`, `lld-link`, `wasm-ld` are symlinks to `lld`:
https://github.com/llvm/llvm-project/blob/c8414fa9410841da20964758c89bf9e312941dfa/lld/tools/lld/CMakeLists.txt#L26-L33

**Pull request merged**
