### PR TITLE
Improve building with LLVM

### PR DESCRIPTION
**Pull request by Inokinoki**
Detect LLVM LD rather than detecting Clang;
Fix broken `-exported_symbols_list` option.

### CODE REVIEW

**Comment by Arfrever** [comment]
LLD is actually group of several linkers, as seen in:
https://github.com/llvm/llvm-project/blob/f2710d4b576053d405af7a0e2a62ea06d5a978e3/lld/tools/lld/lld.cpp#L13-L24
https://github.com/llvm/llvm-project/blob/f2710d4b576053d405af7a0e2a62ea06d5a978e3/lld/tools/lld/lld.cpp#L54-L61
https://github.com/llvm/llvm-project/blob/f2710d4b576053d405af7a0e2a62ea06d5a978e3/lld/tools/lld/lld.cpp#L68-L76

GNU flavor (`ld.lld` or `lld -flavor gnu`) supports `--version-script` option. Other flavors do not.
```
$ echo '{global: *;};' > test
$ ld.lld --version-script=test
ld.lld: error: no input files
$ lld -flavor gnu --version-script=test
lld: error: no input files
$ ld64.lld --version-script=test
ld64.lld: warning: ignoring unknown argument: --version-script=test
ld64.lld: error: -arch not specified and could not be inferred
$ lld -flavor darwin --version-script=test
lld: warning: ignoring unknown argument: --version-script=test
lld: error: -arch not specified and could not be inferred
$ lld-link --version-script=test
lld-link: warning: ignoring unknown argument '--version-script=test'
lld-link: error: no input files
$ lld -flavor link --version-script=test
lld: warning: ignoring unknown argument '--version-script=test'
lld: error: no input files
$ wasm-ld --version-script=test
wasm-ld: error: unknown argument: --version-script=test
wasm-ld: error: no output file specified
wasm-ld: error: no input files
$ lld -flavor wasm --version-script=test
lld: error: unknown argument: --version-script=test
lld: error: no output file specified
lld: error: no input files
```

`ld.lld`, `ld64.lld`, `ld64.lld.darwinnew`, `lld-link`, `wasm-ld` are symlinks to `lld`:
https://github.com/llvm/llvm-project/blob/c8414fa9410841da20964758c89bf9e312941dfa/lld/tools/lld/CMakeLists.txt#L26-L33

GNU flavor (`ld.lld`) seems to support `-exported_symbols_list` option, but expects different syntax of file than Darwin flavor (`ld64.lld`):
```
$ echo a > symbols_list
$ ld.lld -exported_symbols_list symbols_list
ld.lld: error: symbols_list:1: unexpected EOF
>>> a
>>> ^
$ ld64.lld -exported_symbols_list symbols_list
ld64.lld: error: -arch not specified and could not be inferred
```

My suggestion for `configure.ac`:
- Do not try to parse output of `${compiler} --version` or `${linker} --version` or anything.
- Call `${compiler}` with `-Wl,--version-script` / `-Wl,-exported_symbols_list` with valid minimal files and check if it succeeds:
```
echo "int main(){}" > test.cpp
echo "{global: *;}" > test.ver
echo "main" > test.exp
symbols_filtering_option=
if ${CXX} ${CXXFLAGS} ${LDFLAGS} -Wl,--version-script=test.ver -o test test.cpp >/dev/null 2>&1 ; then
  symbols_filtering_option=version-script
elif ${CXX} ${CXXFLAGS} ${LDFLAGS} -Wl,-exported_symbols_list,test.exp -o test test.cpp >/dev/null 2>&1 ; then
  symbols_filtering_option=exported_symbols_list
fi

AM_CONDITIONAL([VERSION_SCRIPT], [test "${symbols_filtering_option}" = "version-script"])
AM_CONDITIONAL([EXPORTED_SYMBOLS_LIST], [test "${symbols_filtering_option}" = "exported_symbols_list"])
```

**Comment by epico** [comment]
Does lld support `--version` option?

**Comment by epico** [comment]
@Arfrever I think checking `lld --version` is more safe than try to link the code.

**Comment by Arfrever** [comment]
```
$ lld --version
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-ld (WebAssembly) instead
$ ld.lld --version
LLD 11.0.0 (compatible with GNU linkers)
$ ld64.lld --version
ld64.lld: warning: ignoring unknown argument: --version
ld64.lld: error: -arch not specified and could not be inferred
$ lld-link --version
LLD 11.0.0
```

> @Arfrever I think checking `lld --version` is more safe than try to link the code.

But we do not know if any flavor of LLD will be even used.
Linker is rarely called directly, usually it is called by compiler driver (by e.g. `gcc`, `g++`, `clang`, `clang++`).
Those compiler drivers accept `-fuse-ld=...` option to override default linker.
`clang -fuse-ld=bfd` calls `ld.bfd` linker.
`clang -fuse-ld=gold` calls `ld.gold` linker.
`clang -fuse-ld=lld` calls `ld.lld` linker (on Linux systems) (maybe it calls `ld64.lld` on Mac OS).

**Comment by epico** [comment]
What is the output of `lld -v` and `lld --version`?

**Comment by Arfrever** [comment]
```
$ lld -v
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-ld (WebAssembly) instead
$ lld --version
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-ld (WebAssembly) instead
```

**Comment by epico** [comment]
Sorry, I mean the output on macOS.

**Comment by epico** [comment]
Thanks, patch merged!

Please improve the patch in another pull request if needed.

**Pull request merged**
