### PR TITLE
Prefer autoreconf over gnome-common

### PR DESCRIPTION
**Pull request by t-chaik**
The gnome-common package is deprecated:

    https://wiki.gnome.org/Projects/GnomeCommon/Migration

### CODE REVIEW

**Comment by epico** [comment]
Thanks for the patch!

**Comment by t-chaik** [comment]
Thanks for merging this @epico! Do you have any idea when the next release of `libpinyin` will be cut? Would be awesome to have one including this.

**Comment by epico** [comment]
I think the next libpinyin release will be one or two months later.

**Comment by t-chaik** [comment]
Ok nice, thank you.

**Pull request merged**
